spring:
  kafka:
    # Kafka ??? ?? ?? ??
    bootstrap-servers: localhost:9092

    producer:
      # Producer? ???? ???? ?? ????? ??? ??
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      # Producer? ???? ???? ?? ????? ??? ??
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

    consumer:
      # Consumer ??? ?? ??? ??
      group-id: basic-group
      # Consumer? ?? ??? ??? ? ?? offset ?? ?? (earliest: ?? ????)
      auto-offset-reset: latest
      # Consumer? ???? ???? ?? ?????? ??? ??
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      # Consumer? ???? ???? ?? ?????? ??? ??
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

server:
  # ? ?????? ??? ???? ?? ??
  port: 8080

# ?? ?? ?? (????)
logging:
  level:
    org.springframework.kafka: INFO
    org.apache.kafka: WARN
